version: '3.7'
services:
  php:
    container_name: evista-php
    build: ./docker/php
    ports:
      - "4000:4000"
    volumes:
      - .:/var/www/http
    networks:
      docker:
        ipv4_address: 172.30.10.8

  nginx:
    container_name: evista-nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/http
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
    networks:
      docker:
        ipv4_address: 172.30.20.8

networks:
  docker:
    external: true